### ISSUE TITLE
Strict-mode compilation

### ISSUE THREAD

**Issue by stepango** [yole/kotlin-style-guide#14]
By strict-mode compilation, I mean compile-time errors for code that does not follow style-guide.

This issue inspired by Python approach where badly formatted code just cannot be executed. I know that  Kotlin and Python do not have much in common, but I hope my point is clear.

There is a lot of different and popular style guides for Java that could affect Kotlin code style in particular project/library. Probably strict-mode approach could bring consistency across all Kotlin code and help get rid of external style-checkers. 

As an option strict-mode could be turned on by default for compilation and turned off by default in REPL.

Does it make sense?
Is it a right place to address this issue?

**Comment by gildor** [comment]
Also, it can be not compilation step, but additional utility like [gofmt](https://blog.golang.org/go-fmt-your-code) for Go, so you can easily integrate code style check step to your build toolchain>

**Comment by yole** [comment]
I'm fairly strongly against such an approach. The effect of strict code style enforcement on developer productivity is entirely negative. Also, if this enforcement is non-optional, it will become a barrier to the adoption of Kotlin, and if it's optional, then it will not reach consistency across all Kotlin code.

We do plan to invest into great formatting tools so that you could get nicely formatted Kotlin code with one keystroke, and you could run the formatter before checkin or at another appropriate time during the development process, so that you will get nicely and consistently formatted code without any effort spent on formatting.

(Also, we have no plans to develop external style checkers at this time, so I'm not sure what's there to get rid of.)

**Comment by yole** [comment]
(Not to mention the simple fact that introducing strict code style enforcement at this time would be a breaking change that would violate our backwards compatibility guarantees.)

**Comment by gildor** [comment]
formatting tool would be really grateful!
